config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show]
  resources :playlists, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def show
    @artist = Artist.find(params[:id])

  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)

    redirect_to @artist
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to artists_path(@artist)
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
    @songs = Song.all
  end

  def create
    @playlist = Playlist.create(playlist_params)

    redirect_to @playlist
  end

  private

  def playlist_params
    params.require(@playlist).permit(:name, song_ids: [])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def show
    @song = Song.find(params[:id])
  end

  private

  def song_params
    params.require(:song).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
    <% if @artist.errors.any? %>
        <h2><%= pluralize(@artist.errors.count, 'error') %> prohibited this record from being saved:</h2>
        <ul>
          <% @artist.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :image_path %>
    <%= f.text_field :image_path %>
    <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h2>Edit artist</h2>

<%= render partial: 'form' %>

app/views/artists/index.html.erb
<h1>All Artist</h1>

<ul>
<% @artists.each do |artist| %>
  <li><%= link_to artist.name, artist_path(artist) %></li>
<% end %>
</ul>

<%= link_to 'New artist', new_artist_path %>

app/views/artists/new.html.erb
<h2>Create new artist</h2>

<%= render partial: 'form' %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>
<%= link_to 'Edit', edit_artist_path(@artist) %>
<%= link_to 'Delete', artist_path(@artist), method: :delete %>
<%= link_to 'New song', new_artist_song_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/index.html.erb
<h2>All playlist</h2>

<%= link_to 'New playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= form_for(@playlist) do |f| %>
    <%= f.text_field :name %>

    <% @songs.each do |song| %>
        <div>
          <%= check_box_tag :song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}" %>
          <%= song.title %>
        </div>
    <% end %>

    <%= f.submit %>
<% end %>

app/views/songs/new.html.erb
<h2>New Song</h2>

<p>Add a new song for <%= @artist.name %></p>
<%= form_for([@artist, @song]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<%= link_to @song.artist.name, artist_path(@song.artist) %>